version: "3.9"

services:
  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/app
    command: >
      sh -c "python3 ./manage.py makemigrations && 
             python3 ./manage.py migrate &&
             python3 ./manage.py runserver 0.0.0.0:8000"
    env_file:
      - ./.env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:14
    volumes:
      - db-data:/var/lib/postgres/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data: