# Generated by Django 4.1 on 2024-04-15 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parser', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageencoding',
            name='file_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
